
export const TYPES = {
    ADD_USER: 'ADD_USER',
    EDIT_USER: 'EDIT_USER',
    DELETE_USER:'DELETE_USER',
    SET_TABLE:'SET_TABLE',
    SEARCH_USER:'SEARCH_USER',
    FILTER_STATUS: 'FILTER_STATUS'

}